name: gipmed-wsi
channels:
  - conda-forge
  - nvidia
  - pytorch
  - sebp
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchaudio
  - torchvision
  - cudatoolkit=11.3
  - ipython
#  - numpy
#  - scipy
#  - scikit-learn
  - scikit-image
  - jupyter
  - jupyterlab
  - matplotlib

  - pandas
#  - cython
#  - pytest
  - tqdm
#  - freetype
#  - plotly
#  - ipykernel
  - pip
#  - python-kaleido
#  - xlrd
#  - scikit-survival
#  - psutil
#  - tensorboard
  - openpyxl
#  - opencv
#  - mesa-libgl-cos6-x86_64
#  - cupti
#  - mesalib
#  - ffmpeg
#  - libsm-cos6-x86_64
#  - xorg-libxext
  - pip:
      - openslide-python
      - opencv-python
      - bresenham
      - lightly
      - wandb
      - gitpython
      - typed-argument-parser